### ISSUE TITLE
console.log only shows first line of output

### ISSUE THREAD

**Issue by kevinansfield** [lostfields/vscode-nodejs-repl#10]
If you use `console.log` to output a string with newline chars (`\n`) the in-editor and REPL output only show the first line.

<img width="440" alt="screen shot 2018-07-04 at 15 13 57" src="https://user-images.githubusercontent.com/415/42281998-0872022c-7f9d-11e8-937b-1976a5564aaf.png">

This tripped me up earlier because I thought the output was being truncated in app code rather than by the repl.

**Comment by lostfields** [comment]
I'll fix it in next release.
