### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by danySam** [lostfields/vscode-nodejs-repl#11]
require() statement not working on windows system.

**Comment by danySam** [comment]
Example:

For the following code, 
`const db= require('../../db')`

I am getting the error
`Error: Cannot find module 'c:\Users\Dany\Projects\db'`

The correct file path is
`C:\Users\Dany\Projects\Express\abApi\db\index.js`

**Comment by lostfields** [comment]
I had problems retrieving the current working directory, but I'll try again. Are you opening your project as folder or workspace?

**Comment by danySam** [comment]
I am opening it as a folder
