### ISSUE TITLE
Objects that has functions as keys are not rendered properly 

### ISSUE THREAD

**Issue by mr-nano** [lostfields/vscode-nodejs-repl#17]
![image](https://user-images.githubusercontent.com/4840723/49338943-aa9c0100-f64f-11e8-8e4e-7eee4fc020a6.png)

While `radius` and `color` are rendered, but `getArea` and `getCircumference` are not.

**Comment by lostfields** [comment]
It can be scary to output result of methods, but I can agree that get/set properties should be outputted.

**Comment by mr-nano** [comment]
Hey, thanks for getting back. I am unsure if I get what you mean by `scary`
Isn't the result of methods, just their to string representation?

**Comment by lostfields** [comment]
It's scary since you don't know what a method does. It can do CRUD operations or whatever you don't want to run when it isn't supposed to. You code is actually running multiple times through REPL. 

But I can make it render get/set properties in a class

```javascript
class cirlce {
    constructor() {
        this.radius = 10
    }

    get area() {
        return Math.PI * this.radius * this.radius
    }
}

new cirlce()
```

**Comment by mr-nano** [comment]
If I get correctly, we won't be running the function, right?

For the above `circle` I defined, I'll expect - 
```
{ "radius" : 10, "color" : orange, 'getArea' : [Function], 'getCircumference' : [Function]
```

Or at max,
```
{ "radius" : 10, "color" : orange, 'getArea' : function() {return Math.PI * this.radius * this.radius}, 'getCircumference' : function() { ... }
```

**Comment by lostfields** [comment]
ok, I see. If that information is of any value I can look into it.

**Comment by mr-nano** [comment]
Yea. In my opinion its valuable otherwise we get a wrong feedback of what exactly is in the object.
