### ISSUE TITLE
console methods info,dir and time does not work

### ISSUE THREAD

**Issue by danielo515** [lostfields/vscode-nodejs-repl#3]
Hello, trying to use any of the mentioned methods results on an error: `  TypeError: _console(...).time is not a function`.

My node version is 9 and the latest VSCode

Your extension is great an awesome, keep it going!

**Comment by lostfields** [comment]
Thanks

I knew that would be a problem one or another time, but forgot all about it. I had to replace the console to track line numbers :-)

I will fix this

**Comment by danielo515** [comment]
Cool! Awesome. No hurry however, having `console.log` is good enough.
Maybe there is something more critical, like support for requires 😄
