### ISSUE TITLE
JavaScript multidimensional array not displaying properly

### ISSUE THREAD

**Issue by omartan** [lostfields/vscode-nodejs-repl#5]
<img width="355" alt="screen shot 2018-04-28 at 09 54 48" src="https://user-images.githubusercontent.com/12379413/39390653-3a45e708-4aca-11e8-82b2-b04a51e726d2.png">

Multi dimensional array is not displayed properly

**Comment by lostfields** [comment]
you are right, this is only fixed for results. I'm going to fix this for console logs as well.

**Comment by mr-nano** [comment]
This problem still exists?

**Comment by lostfields** [comment]
should be fixed and released
