### ISSUE TITLE
Don`t open "output" panel

### ISSUE THREAD

**Issue by yaagma** [lostfields/vscode-nodejs-repl#9]
Every time you type in a js file, the "OUTPUT" panel is automatically focused, changing any other panel you were using (Debug Console, Terminal...). It's very annoying to constantly having to restore the panel you want to work with.

Thanks for this great extension
Raúl
Ps: Sorry for my poor English.

**Comment by lostfields** [comment]
Kind of agree here, since errors and output is in the editor but a few messages can be hard to show. I'll try to look into it.
